name: Build and Release Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build CSS
        run: npm run build:css

      - name: Build Electron app
        run: npm run dist

      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: electron-app
          path: dist/**

      - name: Create a tag
        id: tag
        run: |
          TAG_NAME="v1.0.0-${{ github.run_number }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/* # Upload all files in the dist directory
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
